version: '3'
services:
  centos:
    hostname: centos
    container_name: centos
    image: daocloud.io/centos:7.6
    networks:
      centos_net:
        ipv4_address: 172.21.0.100
networks:
   centos_net:
      ipam:
         config:
         - subnet: 172.21.0.0/16
