version: '3'
services:
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx:1.16.0
    ports:
      - 80:80
      - 443:443
    networks:
      test_net:
        ipv4_address: 192.168.0.10
    restart: always
    volumes:
      - ./conf:/etc/nginx
      - ./application:/usr/share/nginx
networks:
   test_net:
      ipam:
         config:
         - subnet: 192.168.0.0/16

