version: '3'
services:
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx:1.16.0
    ports:
      - 80:80
      - 443:443
    networks:
      nginx_net:
        ipv4_address: 172.20.1.10
    volumes:
      - ./conf:/etc/nginx
      - ./application:/usr/share/nginx
networks:
   nginx_net:
      ipam:
         config:
         - subnet: 172.20.1.0/16

