version: '3'
services:
  slave:
    hostname: slave
    image: newrain857/mysql5.7-ab:slave
    ports:
      - 3307:3306
    networks:
      mysql_net:
        ipv4_address: 172.19.1.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_MASTER_SERVICE_HOST: 172.19.1.2
      MYSQL_REPLICATION_USER: repl
      MYSQL_REPLICATION_PASSWORD: 123456
    depends_on:
      - master

  master:
    user: root
    hostname: master
    image: newrain857/mysql5.7-ab:master
    ports:
      - 3306:3306
    networks:
      mysql_net:
        ipv4_address: 172.19.1.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_REPLICATION_USER: repl
      MYSQL_REPLICATION_PASSWORD: 123456
networks:
   mysql_net:
      ipam:
         config:
         - subnet: 172.19.1.0/16
